/********************************************************************
* src/SampleDescriptorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/SampleDescriptorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSampleDescriptorDict();
extern void G__cpp_setup_inheritanceSampleDescriptorDict();
extern void G__cpp_setup_typetableSampleDescriptorDict();
extern void G__cpp_setup_memvarSampleDescriptorDict();
extern void G__cpp_setup_globalSampleDescriptorDict();
extern void G__cpp_setup_memfuncSampleDescriptorDict();
extern void G__cpp_setup_funcSampleDescriptorDict();
extern void G__set_cpp_environmentSampleDescriptorDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "interface/SampleDescriptor.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SampleDescriptorDictLN_TClass;
extern G__linked_taginfo G__SampleDescriptorDictLN_TBuffer;
extern G__linked_taginfo G__SampleDescriptorDictLN_TMemberInspector;
extern G__linked_taginfo G__SampleDescriptorDictLN_TObject;
extern G__linked_taginfo G__SampleDescriptorDictLN_TNamed;
extern G__linked_taginfo G__SampleDescriptorDictLN_SampleDescriptor;

/* STUB derived class for protected member access */
